#cálculo mva ajustado
original = float(input('Digite o MVA original do produto - usar apenas números e ponto: '))
interna = float(input('Digite o percentual da alíquota interna do ICMS do estado de SP - usar apenas números e ponto: '))
interestadual = float(input('Digite o percentual da alíquota interestadual do ICMS da operação - usar apenas números e ponto: '))
fator_original = float(1 + original / 100)
fator_interna = float(1 - interna / 100)
fator_interestadual = float(interestadual / 100)
fator_aliq_4 = float(100/100 - 4/100)
fator_aliq_12 = float(100/100 - 12/100)
mva_ajustado_4 = float(((fator_original * fator_aliq_4 / fator_interna) - 1) * 100) 
mva_ajustado_12 = float(((fator_original * fator_aliq_12 / fator_interna) - 1) * 100)
print('='*20)
print(input('Para o MVA Original de {:.4}% teremos:\nMVA ajustado para 4% de {:.4}%\nMVA ajustado para 12% de {:.4}%'.format(original, mva_ajustado_4, mva_ajustado_12)))
print('='*20)
print(input('Conferência dos valores:\nfator_orginal: {:.4}\nfator_interna: {:.4}\nfator_interestadual: {:.4}\nfator_aliq_4: {:.4}\nfator_aliq_12: {:.4}\nmva_ajustado_4: {:.4}%\nmva_ajustado_12: {:.4}%'.format(fator_original, fator_interna, fator_interestadual, fator_aliq_4, fator_aliq_12, mva_ajustado_4, mva_ajustado_12)))
print('='*20)
